import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';


export default function signup() {
    return (
        <>
            <Head>
                <title>Create Account</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=' bg-gradient-to-b from-black to-purple-900 h-screen px-8 py-8 sm:h-screen sm:px-16 md:px-20 lg:px-28'>
                <Navbar />

                <form className='bg-gradient-to-br from-purple-800 to-pink-900 shadow-2xl rounded-md py-16 px-10 my-20 mx-auto max-w-md text-center items-center' method="post" action='#'>
                    <h3 className='text-3xl font-bold '>SignUp for Your Account</h3>
                    <ul className='my-10'>
                        <li className='py-3'>
                            <input
                                id="name"
                                name="name"
                                type="name"
                                autoComplete="name"
                                required
                                className="relative block w-full rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-black focus:outline-none focus:ring-black sm:text-sm"
                                placeholder="User Name"
                            />
                        </li>
                        <li className='py-3'>
                            <input
                                id="email-address"
                                name="email"
                                type="email"
                                autoComplete="email"
                                required
                                className="relative block w-full rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-black focus:outline-none focus:ring-black sm:text-sm"
                                placeholder="Email address"
                            />
                        </li>
                        <li className='py-3'>
                            <input
                                id="password"
                                name="password"
                                type="password"
                                autoComplete="password"
                                required
                                className="relative block w-full rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-black focus:outline-none focus:ring-black sm:text-sm"
                                placeholder="Password"
                            />
                        </li>
                        <li className='py-4'>
                            <input
                                type="submit"
                                className="group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                            />
                        </li>
                        <li>

                            <Link href="/login">Alredy Have an Account? <span>Signin</span></Link>

                        </li>
                    </ul>
                </form>
            </main >
        </>
    )
}